# Generated by Django 2.2.2 on 2019-09-21 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint_url', models.CharField(max_length=300)),
                ('headers', models.CharField(max_length=4000)),
                ('params', models.CharField(max_length=4000)),
                ('expected_response_code', models.IntegerField()),
                ('response_code', models.IntegerField()),
            ],
        ),
    ]
